[tool.poetry]
name = "salud-publica-digital"
version = "0.1.0"
description = "Proyecto de Salud Pública Digital"
authors = ["Consultorio Digital"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"
django-crispy-forms = "^2.2"
crispy-bootstrap5 = "^2024.2"
psycopg2-binary = "^2.9.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytest-django (>=4.12.0,<5.0.0)"
]
