# Generated by Django 5.1 on 2026-06-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0008_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='certifica',
            field=models.CharField(max_length=255),
        ),
    ]
