# Generated by Django 5.1 on 2026-06-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0009_alter_consultorio_certifica'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disponibilidad',
            name='unique_disponibilidad',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('profesional', 'fecha', 'hora_inicio')},
        ),
    ]
